### ISSUE TITLE
Primary IP not discovered if device only has primary IPv6 address

### ISSUE THREAD

**Issue by Vittfarne** [jysk-oss/netbox-securecrt-inventory#11]
If a device only has a primary IPv6 address the error "primary ip is not set on device.name" is returned.

I'm guessing it's related to the explicit use of PrimaryIp4 on the lines below, maybe a change to PrimaryIp would be enough? I couldn't get it to built to test.
https://github.com/jysk-oss/netbox-securecrt-inventory/blob/8d04bf6ca566b2cf172598626378468ea5fc912f/internal/inventory/inventory.go#L112-L115
https://github.com/jysk-oss/netbox-securecrt-inventory/blob/8d04bf6ca566b2cf172598626378468ea5fc912f/internal/inventory/inventory.go#L178-L181

**Comment by patrickfnielsen** [comment]
This is a very good point actually.
Just using PrimaryIp should be enough to fix this, I'll get fix up, and publish a new release asap.

**Comment by patrickfnielsen** [comment]
Should be fixed in v0.3.1 - Let me know if you run into any other issues!
