### ISSUE TITLE
Error mapping values

### ISSUE THREAD

**Issue by jckal** [jysk-oss/netbox-securecrt-inventory#3]
Error: yaml: line 15: mapping values are not allowed in this context. 

I'm not familiar enough to know how to troubleshoot this sadly

**Comment by patrickfnielsen** [comment]
Sorry for the late response - can you post the config you used (sanitized) and I'll have a look

**Comment by patrickfnielsen** [comment]
I'll close this as I have not had a response for the last 3 weeks. If you still have issues please let me know and I'll be happy to help.
